name: DwarfMode
version: ${project.version}
main: com.meows.dwarfmode.DwarfModePlugin
api-version: 1.21
author: Eliminator
description: Плагин для гномов, которые живут под землей и не любят вылезать на поверхность
website: https://github.com/yourusername/DwarfMode

commands:
  dwarfmode:
    aliases: [dwm]
    description: Base Dwarf Mode command.
    usage: /<command>
    permission: dwm.cmds
    permission-message: You don't have <permission>

permissions:
  dwm.reload:
    description: Право на перезагрузку конфигурации
    default: op
  dwm.tear:
    description: Право на получение слез гаста
    default: op
  dwm.cmds:
    description: Право на использование команд
    default: true
